package com.evan.effectwallet.util;

public enum WalletStatus {
    DEFAULT,
    CREATE_WALLET_LOADING,
    CREATE_WALLET_SUCCESS,
    CREATE_WALLET_ERROR,
    WALLET_ADD_SUCCESS,
    WALLET_ADD_LOADING,
    WALLET_ADD_ERROR,
    GET_WALLET_BALANCE_LOADING,
    GET_WALLET_BALANCE_SUCCESS,
    GET_WALLET_BALANCE_ERROR,
    INPUT_ERROR,
    GET_WALLET_BALANCE_USD,
    CLEAR_WALLET,
    GET_CHART_DATA_LOADING,
    GET_CHART_DATA_SUCCESS,
    GET_CHART_DATA_FAILED,
    GET_MARKET_DATA
}
